# Generated by Django 6.0.2 on 2026-03-02 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_author_comment_user_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('care', 'Care')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
